version: '3.8'

services:
  backend:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=movie_watchlist_db
      - DATABASE_HOST=postgresdb
      - DATABASE_PORT=5432
    networks:
      - mynetwork

  ui:
    image: frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=movie_watchlist_db
      - DATABASE_HOST=postgresdb
    networks:
      - mynetwork

networks:
  mynetwork:

